const { chromium } = require('playwright');
const http = require('http');
const HOST = 'http://127.0.0.1:8080';
const slots = () => new Promise((res) => http.get('http://127.0.0.1:8080/debug/slots', (r) => { let s = ''; r.on('data', d => s += d); r.on('end', () => res(s)); }));
(async () => {
  const b = await chromium.launch();
  const mk = async () => { const ctx = await b.newContext(); const p = await ctx.newPage(); p.on('pageerror', e => console.log('ERR', e.message)); return { ctx, p }; };
  const a = await mk();
  await a.p.goto(HOST + '/controller', { waitUntil: 'load' });
  await a.p.fill('#name-input', 'Probe'); await a.p.click('#join-btn');
  await a.p.waitForTimeout(1000);
  const tk = await a.p.evaluate(() => localStorage.getItem('tkr-token'));
  console.log('token', tk);
  console.log('slots after join :', await slots());
  await a.ctx.close();
  await new Promise(r => setTimeout(r, 800));
  console.log('slots after close:', await slots());
  const c = await mk();
  await c.p.goto(HOST + '/controller', { waitUntil: 'load' });
  await c.p.evaluate((t) => localStorage.setItem('tkr-token', t), tk);
  await c.p.reload({ waitUntil: 'load' });
  await c.p.waitForTimeout(2000);
  console.log('slots after reclaim:', await slots());
  console.log('view:', await c.p.evaluate(() => document.querySelector('.view.active').id));
  await b.close();
})();